### ISSUE TITLE
Cannot get inside getVoices() object

### ISSUE THREAD

**Issue by aml25** [macdonst/SpeechSynthesisPlugin#7]
I cannot see anything inside the `getVoices()` object that is returned by `speechSynthesis.getVoices()`.  When I do `speechSynthesis.getVoices().length` I can see that there are 9 voices - I'm sure dependent on the device I'm using and OS version.  But when I try `speechSynthesis.getVoices()[0]` it returns undefined.
I'm running this on Android 4.2.2.  I cannot figure out why I can't get this information, and then fill in `SpeechSynthesisUtterance().voiceURI` to change the voice being used.

**Comment by videophonegeek** [comment]
I think you should be writing this as speechSynthesis.getVoices()._list[i].name to keep the javascript lint police quiet.  Did you solve your problem of setting the voice? My frustration is the lack of specifying a male or female voice for deaf users who cannot hear what voice they are selecting! Not a problem with this plugin but the API in general.
